# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0003_auto_20160320_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='dplaresult',
            name='subject_heading4',
            field=models.CharField(default=datetime.datetime(2016, 3, 23, 21, 20, 50, 379736, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dplaresult',
            name='subject_heading5',
            field=models.CharField(default=datetime.datetime(2016, 3, 23, 21, 21, 1, 702083, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dplaresult',
            name='subject_heading6',
            field=models.CharField(default=datetime.datetime(2016, 3, 23, 21, 21, 9, 77081, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
    ]
